version: '3.4'

services:
  abv-calculator:
    image: abv-calculator-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - abv-calculator-db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  
  abv-calculator-db:
    image: mariadb:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: ABV-Calculations
        MYSQL_USER: myuser
        MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080

volumes:
    mariadb: